### ISSUE TITLE
Multiple VLANs from ISP through layer 2 ethernet bridge

### ISSUE THREAD

**Issue by berrfott** [mr-canoehead/network_performance_monitor#12]
I've just installed your network performance monitor, and I'm very excited. But, I've run into a hiccup:

I have fiber from my ISP, and a combined modem/router/switch (CPE). The CPE has both fiber and ethernet interface, and for this experiment I use a fiber media converter since the RaspPi don't have an SFP-HAT. The layer 2 bridge is connected to the media converter on one interface, and the CPE on the other interface. Whilst connected, my internet doesn't work. I guess this is because my ISP utilize four different VLANs connected to four different MAC-addresses on the CPE. (VLAN 190 for ISP-management, VLAN 191 for TV, VLAN 192 for internet and VLAN 193 for VoIP.)

Is there a way for the layer 2 ethernet bridge on the RaspPi to pass all the VLANs through to the CPE? Should there be a notion of this in the Wiki?

**Comment by mr-canoehead** [comment]
Unfortunately this is not a network configuration I am familiar with, so I'm not able to offer any info on how to integrate the bandwidth monitoring component of the project with this setup. If you do discover a solution I'd be happy to add your info to the Wiki and to prepare a network diagram for it.

Thanks,
Chris

**Comment by berrfott** [comment]
I'm sorry. Bridge works perfectly. Typo (by me) in settings messed it up.
