### ISSUE TITLE
Anker AK-A7610011 works for bandwidth monitoring

### ISSUE THREAD

**Issue by christasich** [mr-canoehead/network_performance_monitor#14]
Successfully implemented bandwidth monitoring using 2 x Anker USB 3.0 to RJ45 Gigabit Ethernet Adapter (AK-A7610011). Purchased through [Amazon](https://smile.amazon.com/gp/product/B00NOP70EC) for $16.99 ea.

**Comment by mr-canoehead** [comment]
Thanks for submitting this, I've added this adapter to the list on the [Supported network adapters](https://github.com/mr-canoehead/network_performance_monitor/wiki/Supported-network-adapters) page of the Wiki.
