### ISSUE TITLE
New TP-Link adapter, 1 enet and 3 USB3 ports

### ISSUE THREAD

**Issue by preese** [mr-canoehead/network_performance_monitor#19]
I've just ordered and received a TP-Link Model UE330(UN )USB3 adapter.  What is novel is the traditional enet port AND an additional 3 USB ports in a USB3 hub configuration.

With an empty LAN  enet switch at hand and a few other TP-Link UE300 USB3-enet adapters laying around, I put the UE330(UN) to the test.  I used an RPI4 enet as the root, and then three additional LAN ports, one on the end of the new adapter, and two of the UE300 adapters plugged into the ports of the included hub.  These three planning to use Network Namespaces.

Happy to report, all ports worked as desired, Network Namespaces work on the new adapter port and the 3 USB3 ports on the adapter.

An RPI{3|4}, this adapter and one other USB3-enet adapter, would be all you'd need for the Network Performance Monitor project, 4 usable USB3 ports and two full enet ports.

It was fun to see the Local Network tab have four graphs, one for the RPI wireless, and three for the added LAN connections (I didn't use bridge mode for this desktop project).

In more typical use, the two enet ports could be used for the bridge, and then an USB3-enet adapter plugged into one of the USB3 ports.  With an onboard USB3 ports being used for a USB3 drive, you still have two open USB3 ports for more LAN or faster SSD storage.

The specs on the adapter is:  TP-Link Model UE330(UN), ver 2.0, Part Number 101502012, $19.99 on Amazon.

**Comment by mr-canoehead** [comment]
Thanks for submitting this info, I have added the TP-Link UE330 to the list of supported network adapters.
