### ISSUE TITLE
dashboard report not rendering on ios/ipados 14

### ISSUE THREAD

**Issue by richtw370** [mr-canoehead/network_performance_monitor#23]
first of all thanks for all the hard work and effort on this!  I have had some concerns on my connectivity and this a perfect solution!

right now I have it running on an older MacBook pro that I scrubbed clean and loaded Debian on.

the only issue I have found is that devices running IOS14 or ipados14 cannot view the dashboard.  I tried safari, chrome, brave and duck duck go browser.  all get the same result.  on devices with an earlier OS and all desktops, the report renders fine.

I suspect that the interaction between  ios14 and cdnjs chart.js  is the issue - not sure if it is authentication, the socket connection, or the actual javascript......I did see where there is an issue open for another problem with  Cloudflare access from IOS14, but I am not sure if this would be the same (https://community.cloudflare.com/t/cloudflare-access-broken-on-ios-14/204141).

I apologize if this is not the correct place/process for reporting the issue but I was not sure how best to get in contact.

**Comment by mr-canoehead** [comment]
Thanks for submitting this issue. Unfortunately I don't have access to any iOS devices so I can't assist with troubleshooting, for now I'll leave the issue open and apply the 'help wanted' label; hopefully an iOS wizard will come along and provide a solution / workaround.

Chris

**Comment by dutts** [comment]
Submitted a PR to fix this on Safari under MacOS and iOS

**Comment by mr-canoehead** [comment]
@richtw370 : to patch your system with Richard's fix for this issue:

1) update your local copy of the repository with `git pull`
2) copy `dashboard.html` to the html directory:
`sudo cp network_performance_monitor/netperf/dashboard/html/dashboard.html /opt/netperf/dashboard/html/dashboard.html`
3) refresh the dashboard web page on your client devices - you may need to clear the browser cache to pick up the change.

Thanks,
Chris

**Comment by richtw370** [comment]
I recently got a pi 400 and just built a new instance of this on that device.  Everything works fine and I am able to confirm that on an ipad prod, using ipadOS, the web reports are visible in safari! 

Thanks
