### ISSUE TITLE
Issue Changing from Open Source CLI to Ookla

### ISSUE THREAD

**Issue by jamey** [mr-canoehead/network_performance_monitor#24]
On an installed system, when invoking  install_packages.sh to change from the opensource speed test CLI to the Ookla one, the script fails with this output.

Removing speedtest-cli client...
/home/pi/network_performance_monitor/install_packages.sh: line 99: remove_pip_package: command not found
Adding Ookla repository...

From this point, the script does not install the Ookla CLI and continues to use the open source one.

**Comment by mr-canoehead** [comment]
Thanks for submitting this issue, looks like the remove_pip_package function is indeed missing from `/opt/netperf/scriptutils.sh`
I'll add that function, in the mean time a workaround for switching from `speedtest-cli` to Ookla's speedtest client is:
- uninstall `speedtest-cli`:
`sudo pip3 uninstall speedtest-cli`
- run the package installer script and choose the Ookla client
- run the setup script, it will configure the speedtest client settings in /opt/netperf/config/netperf.json
`sudo /opt/netperf/setup.sh`

After running the setup script the client setting in the speedtest section of /opt/netperf/config/netperf.json should be:
"client": "ookla"
 
Chris

**Comment by jamey** [comment]
Unfortunately, that does not work.  The uninstall fails.

Not uninstalling speedtest-cli at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'speedtest-cli'. No files were found to uninstall.

These are the files in that location.

ls -hald *speed*
drwxr-xr-x 2 root root 4.0K Aug  8 05:01 speedtest_cli-2.0.2.egg-info
-rw-r--r-- 1 root root  61K Jul 14 17:52 speedtest.py

**Comment by richtw370** [comment]
For now I am running the monitor on an old MacBook under Debian.  I was seen 200mb speed for ethernet, which I attributed to the age of the machine.  Just for fun I manually installed the Ookla speed test and it showed 800mb.  I removed it and tried the same process to reconfigure the system.  I got different errors.  I am also willing to test any changes or suggested remedies for this.

**Comment by mr-canoehead** [comment]
I've added the missing remove_pip_package function, I can now switch between the speedtest-cli and Ookla clients by running the package installer script and then updating the speedtest client setting in netperf.json (either 'speedtest-cli' or 'ookla')
