### ISSUE TITLE
iPerf3 not reporting

### ISSUE THREAD

**Issue by JoshuaBLevine** [mr-canoehead/network_performance_monitor#32]
iPerf3 server is running in the background and responds to clients initiating iperf3 tests. However, the local network tab on the performance monitor shows no iperf3 data, and it appears that the database has no row count (0) for iperf3. I started from scratch and this issue is still apparent. I have seen iperf3 servers not display results after a test and only show on the client side, maybe this is the case here as well? 

**Screenshots**
![image](https://user-images.githubusercontent.com/68562637/134963496-2b939d13-d6b9-4667-9559-36e0c4791ae6.png)
![image](https://user-images.githubusercontent.com/68562637/134963547-a6b97435-120d-4f8b-867f-3d36c359d14b.png)

**Comment by mr-canoehead** [comment]
Unable to duplicate.
