### ISSUE TITLE
Changing between speedtest-cli and Ookla cli

### ISSUE THREAD

**Issue by dhanuhammer** [mr-canoehead/network_performance_monitor#34]
**Describe the issue**
I want t ochange to Ookla closed source command line interface to choose my particular server because there are too many substandard speed test servers that give wrong information regarding my speed.

**Supporting information**
none

**Comment by mr-canoehead** [comment]
Switching from the open source speedtest client to the Ookla client should be fairly straightforward:

1) stop the network performance testing tasks
```sudo /opt/netperf/tools/netperf_tasks.sh stop```

2) uninstall the open source speedtest client
```sudo pip3 uninstall -y speedtest-cli```

3) install the Ookla speedtest client; the procedure for installing it can be found on the following Wiki page:

    https://github.com/mr-canoehead/network_performance_monitor/wiki/Install-project-files-and-required-software-packages#install-the-required-os-and-python-packages

4) run the Ookla client to accept the license agreement:
```sudo -u netperf speedtest```

5) get a list of available Ookla speedtest servers:
```speedtest -L```

The output from this command will show a list of servers, e.g.:
``` 
Closest servers:

    ID  Name                           Location             Country
==============================================================================
 14487  Urbanfibre                     Burnaby, BC          Canada
  5799  Tech Futures Interactive Inc.  Burnaby, BC          Canada
  3049  TELUS                          Vancouver, BC        Canada
 16781  TELUS Mobility                 Vancouver, BC        Canada
 17402  Bell Mobility                  Vancouver, BC        Canada
  4243  Shaw Communications            Vancouver, BC        Canada
 17168  Frontier Networks Inc          Vancouver, BC        Canada
  3318  Skyway West Business Internet Services Vancouver, BC        Canada
 22207  BCNET                          Vancouver, BC        Canada
 30165  The Government of British Columbia Vancouver, BC        Canada
```


Note down the ID of the server you wish to use.

6) modify the system settings to use the Ookla client:

```sudo nano /opt/netperf/config/netperf.json```

Change the client settings (in this example I'm using server ID 14487):
```
“client”: “ookla”
“server_id”: 14487
```
If you want the client to choose a server automatically, change the server ID to ```null```:
```“server_id”: null```

7) finally, start the network performance testing tasks:
```sudo /opt/netperf/tools/netperf_tasks.sh start```

The system should now perform scheduled Internet speed tests using the Ookla client.
