### ISSUE TITLE
Non-contributors can't apply labels to issues without an "issue template"

### ISSUE THREAD

**Issue by EvanGoss** [mr-canoehead/network_performance_monitor#7]
If you'd like the "network adapter info" label applied per the [contributing guidelines](https://github.com/mr-canoehead/network_performance_monitor/blob/master/CONTRIBUTING.md), it appears that you need to create an [issue template](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates). Had to Google and came across that approach in a [discussion about users suggesting labels](https://github.com/isaacs/github/issues/148#issuecomment-472856684).

**Comment by mr-canoehead** [comment]
Have created templates for issues related to Network Adapter info, documentation, and the daily report - these templates apply the appropriate labels to the issue.

Thanks,
Chris
