### ISSUE TITLE
known good USB DUAL Ethernet adapter

### ISSUE THREAD

**Issue by farnsaw** [mr-canoehead/network_performance_monitor#9]
I purchased a Vantec USB 3.0 to Dual Gigabit Ethernet Network Adapter (CB-U320GNA) [from Amazon - B00V75ZGO2] to use as my two bridge adapters and it works beautifully.  I get very little (<10%) speed reduction that I can see on this.  I was initially worried as all speedtest-cli runs showed a significantly lower speed than I would have thought it should.  However iperf3 shows full throughput locally AND over the internet.  I have since read that python may be the limiting factor of the speedtest-cli either due to the limited resources of the Pi itself or possibly for other reasons.

Just as a point of knowledge, my configuration is a Pi 4 with 4 GB RAM booting off the SD card with the root partition for the boot pointed at an SSD connected via the USB 3 port.  I am relying on the internal ethernet port for the lan network, the internal Wifi for one of the test beds, and a USB wifi adapter for the other... though I seem to be having problems with that last and it is a "generic" adapter that I have not done any analysis on as I view the wifi test as a lower priority than other issues at the moment.

**Comment by mr-canoehead** [comment]
Thanks for submitting this info, I have added the Vantec adapter to the [Supported network adapters](https://github.com/mr-canoehead/network_performance_monitor/wiki/Supported-network-adapters) page in the Wiki.

This adapter looks ideal for the project! Being a dual NIC adapter it leaves the second USB 3 port on a RPi 4B available for a dual band WiFi adapter. The only issue I see is trying to figure out which RJ45 port maps to which device name assigned by the OS. Are the MAC addresses printed on the device? Does the driver support the ethtool 'identify' command?:

`sudo ethtool -p <interface_name> 60`

This flashes the LED of the RJ45 port for 60 seconds.

Cheers,

Chris

**Comment by farnsaw** [comment]
Chris,
  The MAC addresses are printed on stickers on the adapter, but not easily associated with a specific port.  With 2 minutes prior to running your config it is easy to figure out.  Plug in one port (to a hub/switch/device) and then watch to see which one goes active in the ifconfig.  Put a dot (sticker or ink) over that one and a matching one on the label so you know which MAC is which port..  Bad Picture attached showing the labels, the actual ports are on the not visible left hand side.

ehttool support... I don't know.  I am not familiar enough with network namespaces to run commands on interfaces in other namespaces.

The adapter presents this via USB

Bus 002 Device 005: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
Bus 002 Device 004: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter

to the system so I presume it does.


![IMG_2730](https://user-images.githubusercontent.com/5817337/80921743-2cf98a80-8d46-11ea-8a45-c3c1a4eea03b.jpg)

**Comment by mr-canoehead** [comment]
If you have the time, here's how you can try that `ethtool` command in the `bwmonitor` network namespace:

install the ethtool utility:

`sudo apt install -y ethtool`


open a bash shell as the `pi` user in the `bwmonitor` network namespace:

`sudo ip netns exec bwmonitor sudo -H -u pi bash`

confirm that you're in the `bwmonitor` network namespace:

`ip netns identify $$`

the output should be:

`bwmonitor`

now try the ethtool command:

`sudo ethtool -p <interface_name> 60`

to return to the previous network namespace:

`exit`

**Comment by farnsaw** [comment]
Chris,
  I'm not sure if this is correct or not but it appears they do not support
it, however, I suspect it is something else instead.

pi@gatekeeper:/usr/bin $ ip netns identify
bwmonitor
pi@gatekeeper:/usr/bin $ sudo ethtool -p enx000acd37bfca 60
Cannot identify NIC: Operation not supported
pi@gatekeeper:/usr/bin $ sudo ethtool -p enx000acd37bfc9 60
Cannot identify NIC: Operation not supported
pi@gatekeeper:/usr/bin $ ifconfig
bwmonitor: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::20a:cdff:fe37:bfc9  prefixlen 64  scopeid 0x20<link>
        ether 00:0a:cd:37:bf:c9  txqueuelen 1000  (Ethernet)
        RX packets 2897  bytes 819691 (800.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 696 (696.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enx000acd37bfc9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::20a:cdff:fe37:bfc9  prefixlen 64  scopeid 0x20<link>
        ether 00:0a:cd:37:bf:c9  txqueuelen 1000  (Ethernet)
        RX packets 117422562  bytes 1220247933 (1.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 63979221  bytes 3950996058 (3.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enx000acd37bfca: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::20a:cdff:fe37:bfca  prefixlen 64  scopeid 0x20<link>
        ether 00:0a:cd:37:bf:ca  txqueuelen 1000  (Ethernet)
        RX packets 63979203  bytes 130142841 (124.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 117422667  bytes 1419214645 (1.3 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Andy
